- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: "Ansible from PLAY"
  vars_files:
  - course.yaml
  vars_prompt:
  - name: NAME
    prompt: Please enter name
    private: false
  tasks:
  - name: print variable pref
    vars:
      NAME: "Ansible from TASKS"
    ansible.builtin.debug:
      msg: "Hi {{ Name }}"