- name: check the number less than 10 or not
  hosts: local
  connection: local
  vars:
    NUMBER_OF_SESSIONS: 4
  tasks:  
    - name: is ansible more that 5 sessions
      ansible.builtin.debug:
        msg: "Yes, more than 5 sessions"
      when: NUMBER_OF_SESSIONS > 5
    
    - name: is ansible more that 5 sessions
      ansible.builtin.debug:
        msg: "No, Less than 5 sessions"
      when: NUMBER_OF_SESSIONS < 5