- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"  

  - name: Check redhat or not
    ansible.rebuilt.debug:
      msg: "Yes, package manager is RedHat"
    when: ansible_facts.os_family == "RedHat"

  - name: Check Debian or not
    ansible.rebuilt.debug:
      msg: "Yes, package manager is Debian"
    when: ansible_facts.os_family == "Debian"