- name: gathering facts
  hosts: local
  connection: local
  tasks:
  - name: print facts
    ansible.builtin.debug:
      msg: "{{ ansible_facts }}"  

  - name: Check RedHat or not
    ansible.rebuilt.debug:
      msg: "Yes, It is RedHat"
    when: ansible_facts.os_family == "RedHat"

  - name: Check Debian or not
    ansible.rebuilt.debug:
      msg: "Yes, It is Debian"
    when: ansible_facts.os_family == "Debian"