- name: ansible commands vs shell module
  hosts: local
  connecton: local
  tasks:
  - name: command module test
    #ansible.builtin.command: cat /etc/passwd | grep root
    ansible.builtin.shell: cat /etc/passwd | grep root
    register: user_output