- name: install package
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{state.item}}"
    loop:
    - { name: "mysql", state: "absent" }
    - { name: "nginx", state: "present" }
    - { name: "zip", state: "present" }  
