- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: linux, shell, ansible, terraform
    tagsmap:
      name: ansible
      project: roboshop
      component: catalogue  

    tagslist:  [
              {
                  "key": "name",
                  "value": "ansible"
              },
              {
                  "key": "project",
                  "value": "roboshop"
              },
              {
                  "key": "component",
                  "value": "catalogue"
              }
          ]

  tasks:
  - name: greeting
    ansible.builtin.debug:
      msg: "Hi Raj Kumar, {{ GREETING | default('Good Morning') }}"

  - name: convert strings into list
    ansible.builtin.debug:
      msg: "{{ topics | split(',') }}"
  
  - name: convert map into list
    ansible.builtin.debug:
      msg: "{{ tagsmap | dict2items }}"

  - name: convert list to maps
    ansible.builtin.debug:
      msg:  "{{ tagslist | items2dict }}"